#!/bin/sh

SCREENSHOT_DIR="${HOME}/Pictures/Screenshots"
TIMESTAMP="$(date +'%B %d %Y at %H:%M:%S')"
FILENAME="Screenshot ${TIMESTAMP}.png"
FILEPATH="${SCREENSHOT_DIR}/${FILENAME}"

# Ensure the screenshot directory exists
if [ ! -d "$SCREENSHOT_DIR" ]; then
    mkdir -p "$SCREENSHOT_DIR" && notify-send "Directory Created" "Screenshot directory created at $SCREENSHOT_DIR"
fi

capture_fullscreen() {
    grim "$FILEPATH" && \
    wl-copy < "$FILEPATH" && \
    notify-send -i "$FILEPATH" "Screenshot Taken" "Full screen captured and copied to clipboard."
}

capture_region() {
    REGION=$(slurp)
    [ -z "$REGION" ] && notify-send "Screenshot Cancelled" "No region selected." && exit 1
    grim -g "$REGION" "$FILEPATH" && \
    wl-copy < "$FILEPATH" && \
    notify-send -i "$FILEPATH" "Screenshot Taken" "Region captured and copied to clipboard."
}

case "$1" in
    --monitor|--fullscreen) capture_fullscreen ;;
    --region) capture_region ;;
    *) echo "Usage: $0 [--monitor|--fullscreen | --region]" ;;
esac
