#!/bin/sh
# Autostart system apps in Hyprland

# Desktop 
sleep 1
killall -e xdg-desktop-portal-hyprland
killall xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &

# Polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &